spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:48644/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rEslbrEbQktlfFctBtPCbtiCjJzrVDOB

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=${PORT:8080}
